name: fluffybox
description: Easy to use but powerful storage for all platforms.
version: 0.2.0
homepage: https://krillefear.gitlab.io
repository: https://gitlab.com/KrilleFear/fluffybox
issues: https://gitlab.com/KrilleFear/fluffybox/issues

environment:
  sdk: '>=2.12.4 <3.0.0'

dependencies:
  sqflite_common: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  sqflite_common_ffi: ^2.2.5
  import_sorter: ^4.6.0
  file: ^6.1.4
